FROM python:3.11-slim

WORKDIR /app

# Copier les requirements
COPY app/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copier l'application
COPY app/ .

# Exposer le port Streamlit
EXPOSE 8501

# Lancer Streamlit
ENTRYPOINT ["streamlit", "run", "streamlit_app.py", "--server.port=8501", "--server.address=0.0.0.0"]
